<html>
	<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
	</head>
	<body>
<div>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand -->
  <a class="navbar-brand" href="#">Sistema</a>
  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" href="/">Incio</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/produtos">Lista Produtos</a>
    </li>
    <!-- Dropdown -->
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
        Cadastros
      </a>
      <div class="dropdown-menu">
        <a class="dropdown-item" href="/listaClientes">Lista Clientes</a>
        <a class="dropdown-item" href="/produtos">Lista Produtos</a>
        <a class="dropdown-item" href="/incluirProduto">Incluir Produto</a>
      </div>
    </li>  </ul>
</nav>
</div>
	<div>
		<?= $this->content() ?>
	</div>	
	</body>
</html>